First drop of react unit tests
redhat-developer/vscode-granite pull request #111
Opened 2024-10-24 23:57 UTC by neehar18

2024-10-25 00:10 UTC, neehar18 commented
@fbricon the CI build failure is because there are conflicting type definitions between the installed versions of @types/mocha and @types/jest. 

Since I am using Jest for testing, can I remove @types/mocha from devDependencies?

2024-10-26 12:40 UTC, fbricon requested changes
You should not have a conflict between mocha and jest since the main package doesn't and shouldn't be concerned about react and jest

2024-10-26 12:40 UTC, fbricon commented on package.json
> +    }
those changes seem unnecessary, since the tests only affect the webviews/ package

2024-10-26 12:40 UTC, fbricon commented on package.json
> +    "test:ci": "jest --ci --reporters=default --reporters=jest-junit"
this should delegate the jest tests from the webviews package

2024-10-26 12:40 UTC, fbricon commented on webviews/src/StatusCheck.tsx
> +import React from 'react';
seems unnecessary

2024-10-26 12:40 UTC, fbricon commented on webviews/src/App.tsx
> +import React from 'react';
seems unnecessary

2024-10-29 10:46 UTC, fbricon commented on package.json
> +    "test:ci": "cd webviews && jest --ci --reporters=default --reporters=jest-junit"
test:ci seems unused

2024-10-29 10:47 UTC, fbricon commented on webviews/src/ProgressBar.test.tsx
> +//import React from 'react';
don't comment, delete

2024-10-29 10:47 UTC, fbricon commented
the build fails and there are conflicts to fix

2024-10-31 09:13 UTC, neehar18 commented
Closing the PR as this is addressed in https://github.com/redhat-developer/vscode-granite/pull/123

2024-10-31 09:13 UTC, closed without merging