Only show the welcome page the first time the extension starts
redhat-developer/vscode-granite pull request #56
Opened 2024-09-30 06:11 UTC by lavanyaj3

added and store a flag in global storage (hasRunSetup) and tested against an environment variable (OLLAMA_MOCK). Once all the models are installed then the welcome page will not pop up

2024-09-30 06:53 UTC, fbricon requested changes

2024-09-30 06:53 UTC, fbricon commented on src/extension.ts
> +  const isDevMode = process.env.OLLAMA_MOCK === 'true';
no, this is not enough to determine you're in dev mode. https://github.com/redhat-developer/vscode-granite/blob/main/.vscode/launch.json#L19 is also in dev mode. Right now, dev mode is inferred from Context.extensionMode, in https://github.com/redhat-developer/vscode-granite/blob/main/src/panels/setupGranitePage.ts#L71, but that's not satisfying either. You could run another VS Code extension in Dev Mode and that would make this one enter in dev mode as well.

What is needed is a refactoring, where isDevMode is moved to https://github.com/redhat-developer/vscode-granite/blob/main/src/commons/constants.ts
- `export const isDevMode = process.env.GRANITE_EXT_DEV_MODE === 'true';`
- add GRANITE_EXT_DEV_MODE env var to both launch configs in https://github.com/redhat-developer/vscode-granite/blob/main/.vscode/launch.json
- replace extensionMode by isDevMode in the constructor in https://github.com/redhat-developer/vscode-granite/blob/main/src/panels/setupGranitePage.ts#L53

2024-10-01 09:29 UTC, fbricon commented on src/extension.ts
> +  const isDevMode = process.env.OLLAMA_MOCK === 'true';
remove that line

2024-10-01 12:59 UTC, fbricon commented on src/extension.ts
> +  if (!hasRunBefore || isDevMode) {
you need to import isDevMode

2024-10-01 13:11 UTC, lavanyaj3 commented on src/extension.ts
> +  if (!hasRunBefore || isDevMode) {
added but the build is failing

2024-10-01 13:33 UTC, lavanyaj3 commented on src/extension.ts
> +  if (!hasRunBefore || isDevMode) {
done

2024-10-01 15:17 UTC, fbricon approved these changes

2024-10-01 15:20 UTC, merged

2024-10-01 15:22 UTC, fbricon commented
Thanks @lavanyaj3 

I had to recreate a single commit and kept a linear history, forced pushed to your branch before I could merge it.

2024-10-02 07:27 UTC, lavanyaj3 commented
Will work on linear commits history in main branch from next tickets.