Updating Readme.md file
redhat-developer/vscode-granite pull request #57
Opened 2024-09-30 07:34 UTC by athirakm94

updating Readme.md file

2024-09-30 11:11 UTC, fbricon commented on README.md
> +In this project,we are building local AI co-pilot using **Granite Code, Ollama, and Continue**,where we utilize a collection of open-source components to implement a feature-rich developer co-pilot i
- add hyperlinks to Granite Code, Ollama and Continue websites
- add spaces after commas

2024-09-30 11:14 UTC, fbricon commented on README.md
> +**Recommendation:** Model Size 20B for chat, 8B for tab code completion.
@jamescho72 are we sticking with those recs?

2024-09-30 11:15 UTC, fbricon commented on README.md
> +  * OS: MacOS
Nope, extension works cross platform

2024-09-30 11:16 UTC, fbricon commented on README.md
> +  * optional: [gh](https://cli.github.com/) to manage pull requests.
No this is for development only. Those belong to the contributing guide.

2024-09-30 11:19 UTC, fbricon commented on README.md
> +  * Install [continu.dev](https://marketplace.visualstudio.com/items?itemName=Continue.continue) extention on Visual studio code
```
The [Continue.dev](...) extension should be installed automatically as a dependency. If not, please install it manually.
```

2024-09-30 11:26 UTC, fbricon commented on README.md
> +This will install the dependencies for the extension and its [webview(s)](https://code.visualstudio.com/api/extension-guides/webview)
No, this belongs to the contributing guide. You should have a paragraph that links to it

2024-09-30 11:29 UTC, fbricon commented on README.md
> +
Until the extension is available in the Marketplaces, you can explain how you can download the vsix from the GH releases page, and how to install it.

2024-09-30 11:33 UTC, fbricon commented on README.md
> +#### Use Vscode-granite UI to install extention and models
Setup the Granite Code models as your code assistant.

2024-09-30 11:34 UTC, fbricon commented on README.md
> +![runextension](/media/installandrun.gif)
No, that belongs to the contributing guide

2024-09-30 11:39 UTC, fbricon commented on README.md
> +
The first time the vscode-granite extension starts, the Granite Code setup wizard will open. You can open this wizard any time, from the command palette, execute the "Granite: Setup Granite Code as code assistant" command.

2024-09-30 11:45 UTC, fbricon commented on README.md
> +![installollama](media/installollama.gif)
If Ollama is not installed, installation options are displayed:

- Install with Homebrew: if Homebrew is detected on your machine (Mac/Linux)
- Install with Script: on Linux
- Install Manually: on all platforms

Installing via Homebrew or Script will run the installation command in a VS Code Terminal. If you install Ollama manually, you'll be redirected to the Ollama download page.

Once OIlama is installed, the page will be refreshed automatically.

2024-09-30 11:48 UTC, fbricon commented on README.md
> +* Quickly use documentation as context
move under "why ollama" section above

2024-09-30 11:50 UTC, fbricon commented on README.md
> +![installmodels](media/installmodels.gif)
Once the models are pulled into Ollama, Continue will be configured automatically to use them, the Continue chat view will open.

2024-10-07 06:30 UTC, fbricon commented
- please rebase your PR against main
- the UI [changed](https://github.com/redhat-developer/vscode-granite/pull/66), so please use newer screenshots

2024-10-07 17:33 UTC, fbricon commented on README.md
> +**Recommendation:** Model Size 20B for chat, 8B for tab code completion.
@athirakm94 so 8b/8b it is

2024-10-09 10:15 UTC, fbricon requested changes
Please delete the unnecessary images.

2024-10-09 10:15 UTC, fbricon commented on README.md
> +In this project,we are building local AI co-pilot using [Granite Code](https://github.com/ibm-granite/granite-code-models), [Ollama](https://ollama.com/), and [Continue](https://www.continue.dev/), w
> We aim to implement a feature-rich local AI co-pilot for Visual Studio Code, by utilizing a collection of open-source components: [Granite Code](https://github.com/ibm-granite/granite-code-models), [Ollama](https://ollama.com/), and [Continue](https://www.continue.dev/). By running Granite models locally, we ensure compliance with data privacy and licensing requirements. Our integration focuses on working with Continue to seamlessly interact with Visual Studio Code, helping developers streamline their workflow, boost productivity, and write higher-quality code.

2024-10-09 10:15 UTC, fbricon commented on README.md
> +</p>
please remove that image

2024-10-09 10:15 UTC, fbricon commented on README.md
> +* Quickly use documentation as context
remove empty lines

2024-10-09 10:15 UTC, fbricon commented on README.md
> + </p>
remove unnecessary paragraph

2024-10-09 10:20 UTC, fbricon commented on README.md
> +<p></p>
don't use html tags. This is markdown

2024-10-11 13:35 UTC, athirakm94 commented
Hi @fbricon,  as  i have raised PR from main branch , i am planning to reset all the changes done in the main branch of my forked repository ,so there might be a chance to affect this PR as well , i will raise new PR from my feature branch after all the changes

2024-10-11 13:53 UTC, closed without merging