Add error handling
redhat-developer/vscode-granite pull request #61
Opened 2024-10-01 16:08 UTC by neehar18

In reference to: https://github.com/redhat-developer/vscode-granite/issues/5

2024-10-01 16:16 UTC, neehar18 commented
Here are my test results from mockServer.ts:

* For the case when there are errors during the pull:

<img width="1416" alt="Screenshot 2024-10-01 at 9 21 47 PM" src="https://github.com/user-attachments/assets/127ab3a9-eb2b-4790-b902-2dc5eb241953">


* For the case when there is a mismatch in the configuration:

<img width="1412" alt="Screenshot 2024-10-01 at 9 27 33 PM" src="https://github.com/user-attachments/assets/43ea6ac5-6794-480c-ace9-fe20974c5dd3">

2024-10-01 16:32 UTC, fbricon requested changes

2024-10-01 16:32 UTC, fbricon commented on webviews/src/App.tsx
> +      }
this block is never reached

2024-10-01 16:32 UTC, fbricon commented on src/ollama/mockServer.ts
> +        // }
please uncomment

2024-10-01 16:32 UTC, fbricon commented on src/ollama/mockServer.ts
> +    // }
please uncomment

2024-10-01 16:32 UTC, fbricon commented on src/panels/setupGranitePage.ts
> -      }
No you need to keep it or else you'll get an error popup. User cancelled on purpose, so no popup is necessary IMO.
<img width="537" alt="Screenshot 2024-10-01 at 18 29 46" src="https://github.com/user-attachments/assets/3a3b109f-f7e7-4eeb-a5b3-fb243c67d028">

2024-10-02 08:23 UTC, fbricon approved these changes

2024-10-02 08:25 UTC, merged

2024-10-02 08:25 UTC, fbricon commented
Thanks @neehar18